### ISSUE TITLE
Server not starting after update, port 8080 blocked

### ISSUE THREAD

**Issue by RafaelSchridi** [linuxserver/docker-sabnzbd#82] opened 2020-08-17 13:38 UTC
Watchtower recently updated my version 3.0.0 and since then sabnzbd just won't start. All i get in the log is 
>Fatal error:, Unable to bind to port 8080 on localhost. Some other software uses the port or SABnzbd is already running.

I tried changing the outgoing port in docker to 8081 and changing the config file to also use port 8081 but that did nothing since it's always forced to 8080.

here is my config
```
   sabnzbd:
        container_name: sabnzbd
        restart: unless-stopped
        volumes:
            - '/opt/x/settings/sabnzbd:/config'
            - '/zfs/x/Content/Complete:/downloads'
        environment:
            - PGID=1001
            - PUID=1001
            - TZ=Europe/Amsterdam
        ports:
            - '8080:8080'
        image: linuxserver/sabnzbd
        networks:
            net:
                ipv4_address: 172.50.0.100
```

It shares the network with other services but disabling those did nothing

```
networks:
  net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.50.0.0/16
```
I have now returned to 2.3.9-0ubuntu1jcfp218.04-ls67

------------------------------

## Expected Behavior
I expect it to start and not complain about any used ports since it resides in a docker container.

## Current Behavior
Doesn't start due to the above mentioned error.

## Steps to Reproduce

1. run the docker compose file
2. look at logs
3. see it restarting

## Environment
**OS:** Arch      
**CPU architecture:** x86_64    
**How docker service was installed:** Composer file     

## Command used to create docker container (run/create/compose/screenshot)
sudo docker-compose pull && sudo docker-compose up -d --remove-orphans

## Docker logs
https://pastebin.com/raw/iY5vL4Vv

**Comment by aptalca** [comment] 2020-08-18 00:24
It looks like sabnzbd keeps crashing. Look through the logs in the config folder to see if the reason is logged

**Comment by ajschroeder** [comment] 2020-08-18 04:57
I am experiencing the same issue, watchtower upgraded sabnzbd to version 3, and it produces the following log output over and over:
```
sabnzbd      | Fatal error:
sabnzbd      |   Unable to bind to port 8080 on localhost. Some other software uses the port or SABnzbd is already running.
```

I am launching everything from a docker-compose file, here is my config:
```
  sabnzbd:
    image: linuxserver/sabnzbd:latest
    container_name: sabnzbd
    restart: unless-stopped
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
    volumes:
      - /docker/containers/sabnzbd/config:/config
      - ./Download/Complete:/downloads
      - ./Download/Incomplete:/incomplete-downloads
    ports:
      - '8080:8080'
      - '9090:9090'
```

I have also reverted back to 2.3.9-0ubuntu1jcfp218.04-ls67 and it is running as expected. 

My server is x86_64 and runs Ubuntu 18.04. I would be glad to post any other relevant information but note that the sabnzbd.log file stopped being updated when the docker container was upgraded.

**Comment by millermarkj** [comment] 2020-08-18 13:13
I'm experiencing the exact same issue.

**Comment by RafaelSchridi** [comment] 2020-08-18 14:29
> It looks like sabnzbd keeps crashing. Look through the logs in the config folder to see if the reason is logged

The last log before I reverted was on the the 15th just before it updated.
Going back to 3.0.0 now also produces no logs.

**Comment by aptalca** [comment] 2020-08-18 16:52
Can you guys give this image a try? `lsiodev/sabnzbd:3.0.1-pkg-c85b429a-dev-e6230341f773975fc25d77fb61baa438f9cdcb04`
replace `linuxserver/sabnzbd` with `lsiodev/sabnzbd:3.0.1-pkg-c85b429a-dev-e6230341f773975fc25d77fb61baa438f9cdcb04` and recreate. See if that works

**Comment by RafaelSchridi** [comment] 2020-08-18 17:05
> Can you guys give this image a try? `lsiodev/sabnzbd:3.0.1-pkg-c85b429a-dev-e6230341f773975fc25d77fb61baa438f9cdcb04`
> replace `linuxserver/sabnzbd` with `lsiodev/sabnzbd:3.0.1-pkg-c85b429a-dev-e6230341f773975fc25d77fb61baa438f9cdcb04` and recreate. See if that works

Getting the same error as before and the last thing in sabnzbd.log is v2.3.9 shutting down   

https://pastebin.com/raw/rTAGiEa8 here are the docker logs but they appear to be identical too.

**Comment by aptalca** [comment] 2020-08-18 17:27
Can you just try a temporary container with `docker run -d --rm --name test -p 8888:8080 linuxserver/sabnzbd` and see if you can go through the wizard on port `8888`?
Once done, you can do `docker stop test` and it should be automatically removed.

**Comment by RafaelSchridi** [comment] 2020-08-18 17:35
Doing that works perfectly and I get can get through the wizard without any problems.
Is there some config issue with going from v2 to v3?

**Comment by aptalca** [comment] 2020-08-18 17:37
No idea, this probably should be brought up in sabnzbd forums as it seems to be a sab issue. I can't reproduce it as my local installs migrated from 2 to 3 successfully.

**Comment by RafaelSchridi** [comment] 2020-08-18 17:41
Moving my /config location to a new empty one didn't fix it either, so it isn't config problem.    
Did you try to reproduce it with the Composer file?

**Comment by aptalca** [comment] 2020-08-18 17:50
Please clarify `Moving my /config location to a new empty one didn't fix it either`
I just tried compose with a new container and a folder mapping and no issues there either

**Comment by RafaelSchridi** [comment] 2020-08-18 17:55
Wait my bad i messed up there, i moved my sabnzbd.ini, but i forgot about sabnzbd.ini.bak and it recovered that.

I moved both of those and it starts up again, I can get past the wizard and everything seems good so far. Seems like some kind of config problem moving from V2>V3

**Comment by RafaelSchridi** [comment] 2020-08-18 18:34
OK I think I've figure it out because the error appeared again. And I can can reproduce it in another container.

First make the container 
`docker run -d  --name test -p 8888:8080 linuxserver/sabnzbd`
Then go though the setup wizard and restart the container
`docker restart test`
And when i look in the logs 
`docker logs test`
its full of
`Fatal error:
  Unable to bind to port 8080 on localhost. Some other software uses the port or SABnzbd is already running.`

**Comment by aptalca** [comment] 2020-08-18 18:49
Can't reproduce here. I created a container with that run, went through the wizard (had to set up a bogus server, which I promptly disabled).
Then restarted. It still works fine.

**Comment by manpreetsnehra** [comment] 2020-08-19 17:14
I tried everything 
1. Upgrade directly : stop container, remove container, upgrade image, start container
2. Remove config : stop container, remove container, delete ALL CONfig, start container -> container starts config done and restart container -> container fails same error 

Fatal error:
  Unable to bind to port 8080 on localhost. Some other software uses the port or SABnzbd is already running.

**Comment by aptalca** [comment] 2020-08-19 17:17
It could be a docker system issue maybe. What's the host OS and how did you install docker service?

**Comment by RafaelSchridi** [comment] 2020-08-19 17:31
I'm on Arch kernel 5.4.51-1-lts and docker version 19.03.12-ce, build 48a66213fe
I'm gonna try a system upgrade and see if that fixes anything.

**Comment by fastlorenzo** [comment] 2020-08-25 13:36
Same issue with kubernetes v1.18.8 on RPi4 (kernel 5.4.51-v7l+) (docker v19.3.12-ce)

**Comment by bradwtracy** [comment] 2020-08-31 14:17
Same issue here as welll.  Docker version 19.03.12, build 48a66213fe running on Ubuntu 20.04

I can remove the sabconfig.ini file(s) and it will come up successfully for the initial config but fail just after that into the same loop complaining about 8080 being in use.  

Reverting to 2.3.9-0ubuntu1jcfp218.04-ls67 works correctly

**Comment by markrawls** [comment] 2020-08-31 22:47
I migrated from baremetal to Docker on an Ubuntu host and was trying to debug this same issue. `sabnzbd` somehow got installed as a `snap` on my system in addition to the regular binary, and chose to run itself on startup.

You can tell if this happened to you by running:

```
$ snap list
Name     Version        Rev    Tracking         Publisher   Notes
# Unrelated things snipped
sabnzbd  3.1.0-develop  1532   latest/stable    safihre     -
```

If that's the case, you can do:

```
$ snap remove sabnzbd
sabnzbd removed
```

...which will delete the snap and stop it from running on startup. After doing that I rebuilt and restarted my docker containers on the `:latest` tag and everything is working once more.

If that's not the issue you're having, you can see specifically what's running on port 8080 like so:

```
$ lsof -nP -iTCP -sTCP:LISTEN | grep 8080
python3   60039            plex    5u  IPv4 216509      0t0  TCP *:8080 (LISTEN)
```

The second column is the PID. To see more details about the process, you can do:

```
$ ps aux | grep 60039  # replace this with whatever your PID is from lsof
plex       60039  1.6  0.6 1957768 53328 ?       Ssl  22:28   0:07 python3 /app/sabnzbd/SABnzbd.py --config-file /config --server 0.0.0.0:8080
```

The part after the runtime stamp there is the full command used to start the process. What I showed above is (roughly) what it should look like if the container is working properly.

Using that information it should be pretty easy to hunt down what's currently listening on 8080.

Hopefully this helps other people debug a little bit!

**Comment by bradwtracy** [comment] 2020-09-08 16:50
Finally had some time to look into this issue further since the Python 2 version was working fine for me.  

Putting strace on the python3 command to start sab results in the following:

`11843 socket(AF_INET6, SOCK_STREAM|SOCK_CLOEXEC, IPPROTO_TCP) = -1 EAFNOSUPPORT (Address family not supported by protocol)
11843 getpid()                          = 11843
11843 write(1, "\nFatal error:\n  Unable to bind t"..., 122) = 122
11843 write(1, "\n", 1)                 = 1`

Note that my Ubuntu host has IPV6 disabled hence the EAFNOSUPPORT error.  I suspect this may be the case as well for others encountering this issue and why you likely can't reproduce it @aptalca .

I have IPV6 disabled on my host for a specific reason.   Likely the easiest workaround is to just enable IPV6 on the host.  

I tried to find why Python was attempting to bind on IPV4 and IPV6 when it was brought up.  It was down to the following in the containers /etc/hosts file:

`::1     localhost ip6-localhost ip6-loopback`

Removing localhost from the ::1 line (::1     ip6-localhost ip6-loopback) resolves the issue but I had to add some sed logic to the run script in order to remove it which isn't ideal.

**Comment by aptalca** [comment] 2020-09-08 17:18
@bradwtracy thanks for troubleshooting, that's great to know.

We generally don't recommend disabling ipv6 on host as it causes issues with a bunch of of our images (anything with iptables and some others).

We'll look into it

**Comment by fastlorenzo** [comment] 2020-10-09 06:58
has this been addressed in the latest version? I don't think the issue should be closed for now

**Comment by aptalca** [comment] 2020-10-09 10:37
Likely won't (can't) be fixed on our end because the ipv6 issue is way upstream of us

**Comment by JDtheHutt** [comment] 2020-10-09 19:04
I have also just experienced this issue.  IPv6 is also disabled across my system for my own reasons and Sabnzbd just outright dies.  Have reverted back to the same version as the others have mentioned, 2.3.9-0ubuntu1jcfp218.04-ls67, and it works perfectly.  It mentions not being able to identify an IPv6 address but it is just noted and carries on loading up fine.

**Comment by RafaelSchridi** [comment] 2020-10-15 00:16
I can't remember why I turned off IPv6, but turning it back on fixed it and everything has been running normally for a week now.

**Comment by kb8080** [comment] 2021-01-27 17:57
Has there been any resolution to this issue? I had this issue with my docker host and ipv6 disabled so I re-enabled ipv6 which allowed me to successfully move from 2.3.9-0ubuntu1jcfp218.04-ls67 to using the latest tag. That said, I just pulled the 'latest' tagged image as of 5 days ago it looks like and I am now receiving that same error once again "unable to bind to port 8080 on localhost" error. Anyone determine what the root cause is or steps to mitigate other than having to revert back to the 2.3.9 image?

**Comment by And2Devel** [comment] 2021-02-24 16:16
I have solved this, without changing my configuration of IPv6 or anything. The devil lies in providing IP address (0.0.0.0) in command line, here:
`python3 /app/sabnzbd/SABnzbd.py --config-file /config --server 0.0.0.0:8080`

I found out that our app works also when we'll specify only port, so my suggestion is to change it in the containter source code to:
`python3 /app/sabnzbd/SABnzbd.py --config-file /config --server :8080`

Till this change will happen in the container code (I really hope for it), following [this guide](https://blog.linuxserver.io/2019/09/14/customizing-our-containers/), I simply added a custom script which changes the above command line, removing 0.0.0.0.

### remove-addr.sh
```
#/bin/bash
ADDR="0.0.0.0"

for FILE in /etc/services.d/sabnzbd/run /var/run/s6/services/sabnzbd/run
do
        if [ -f "${FILE}" ]; then
                sed -i "s/$ADDR//g" $FILE
        fi
done
```
This script should be added to /config/custom-cont-init.d directory, and as we're mounting this externally, it should be easy, for example:

if volumes section of our container looks like that:
```
    volumes:
      - /etc/docker/sabnzbd:/config
      - ...
```


then, on the host, the script should be here:
`/etc/docker/sabnzbd/custom-cont-init.d/remove-addr.sh`

_Note: in WebGUI of SABnzbd, the "General" section in configuration will have an empty field for **SABnzbd Host** - please leave it like that._

**Closed** 2021-08-09 20:51 UTC
Labels: no-issue-activity
