### ISSUE TITLE
Version 3.2.0 Does Not Have Unrar

### ISSUE THREAD

**Issue by x-radeon** [linuxserver/docker-sabnzbd#101] opened 2021-03-12 11:17 UTC
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

## Expected Behavior
Docker image should have Unarar packaged with it.

## Current Behavior
Sab complains about Unrar not being available.

## Steps to Reproduce
1. Update docker to lastest or version-3.2.0 tag
2. Notice error on Sab start

## Environment
**OS:**
Unraid Docker
**CPU architecture:** x86_64/arm32/arm64
x86_64
**How docker service was installed:**
Unraid Community App Store

## Command used to create docker container (run/create/compose/screenshot)
/usr/local/emhttp/plugins/dynamix.docker.manager/scripts/docker run -d --name='sabnzbd' --net='bridge' -e TZ="America/Denver" -e HOST_OS="Unraid" -e 'PUID'='1000' -e 'PGID'='100' -p '8081:8081/tcp' -v '/mnt/user/shares/raw/complete/':'/downloads':'rw' -v '/mnt/user/shares/raw/incomplete/':'/incomplete-downloads':'rw' -v '/mnt/user/appdata/sabnzbd':'/config':'rw' 'linuxserver/sabnzbd'

## Docker logs
2021-03-12 04:06:07,006::INFO::[SABnzbd:425] par2 binary... found (/usr/bin/par2)
2021-03-12 04:06:07,007::INFO::[notifier:122] Sending notification: Error - unrar binary... NOT found! (type=error, job_cat=None)
2021-03-12 04:06:07,007::ERROR::[SABnzbd:444] unrar binary... NOT found!
2021-03-12 04:06:07,008::INFO::[SABnzbd:450] 7za binary... found (/usr/bin/7za)
2021-03-12 04:06:07,008::INFO::[SABnzbd:461] nice binary... found (/usr/bin/nice)
2021-03-12 04:06:07,008::INFO::[SABnzbd:465] ionice binary... found (/usr/bin/ionice)
2021-03-12 04:06:07,009::INFO::[notifier:122] Sending notification: Error - Essential modules are missing, downloading cannot start. (type=error, job_cat=None)
2021-03-12 04:06:07,009::ERROR::[SABnzbd:471] Essential modules are missing, downloading cannot start.

**Comment by tommycahir** [comment] 2021-03-12 11:28
Yip I am seeing the same thing
My docker logs below also:
```
2021-03-12 11:20:11,863::INFO::[__init__:331] All processes started
2021-03-12 11:20:11,863::INFO::[SABnzbd:307] Template location for Glitter is /app/sabnzbd/interfaces/Glitter
2021-03-12 11:20:11,863::INFO::[SABnzbd:307] Template location for Config is /app/sabnzbd/interfaces/Config
2021-03-12 11:20:11,864::INFO::[misc:1053] [N/A] Running external command: ['/usr/bin/par2', '-h']
2021-03-12 11:20:11,872::INFO::[SABnzbd:401] SABYenc module (v4.0.2)... found!
2021-03-12 11:20:11,873::INFO::[SABnzbd:420] Cryptography module (v3.4.6)... found!
2021-03-12 11:20:11,873::INFO::[SABnzbd:425] par2 binary... found (/usr/bin/par2)
2021-03-12 11:20:11,873::INFO::[notifier:122] Sending notification: Error - unrar binary... NOT found! (type=error, job_cat=None)
2021-03-12 11:20:11,873::ERROR::[SABnzbd:444] unrar binary... NOT found!
2021-03-12 11:20:11,873::INFO::[SABnzbd:450] 7za binary... found (/usr/bin/7za)
2021-03-12 11:20:11,874::INFO::[SABnzbd:461] nice binary... found (/usr/bin/nice)
2021-03-12 11:20:11,874::INFO::[SABnzbd:465] ionice binary... found (/usr/bin/ionice)
2021-03-12 11:20:11,874::INFO::[notifier:122] Sending notification: Error - Essential modules are missing, downloading cannot start. (type=error, job_cat=None)
2021-03-12 11:20:11,874::ERROR::[SABnzbd:471] Essential modules are missing, downloading cannot start.
2021-03-12 11:20:11,875::INFO::[SABnzbd:1431] Starting web-interface on 0.0.0.0:8080
2021-03-12 11:20:11,875::INFO::[_cplogging:216] [12/Mar/2021:11:20:11] ENGINE Bus STARTING
2021-03-12 11:20:11,980::INFO::[_cplogging:216] [12/Mar/2021:11:20:11] ENGINE Serving on http://0.0.0.0:8080
2021-03-12 11:20:11,980::INFO::[_cplogging:216] [12/Mar/2021:11:20:11] ENGINE Bus STARTED
```

I actually seen this in sabnzbd a few days ago and thought it was my non docker install so switched to this containerised version yesterday which worked fine until an update this morning.

**Comment by JanHO22** [comment] 2021-03-12 12:21
Issue is that there is "unrar-nonfree" in /usr/bin and sabnubd is needs "unrar". Quick and dirty fix to get the container running is just adding a hard-link named "unrar" to "unrar-nonfree in /usr/bin.

**Comment by tommycahir** [comment] 2021-03-12 12:24
I have moved back to tag `3.1.1-ls16` and pulled following image as a temp workaround ghcr.io/linuxserver/sabnzbd:3.1.1-ls16 until this gets fixed or changes needed get communicated by sabnzbd themselves, this is not just linuxserver issue as I seen the issue on install direct on ubuntu before moving to this container.

**Comment by Roxedus** [comment] 2021-03-12 12:25
This is a change done upstream in the Ubuntu repositories.

**Comment by Safihre** [comment] 2021-03-12 12:31
@jcfp any clue whats going wrong? We had similar report on the forum.

**Comment by Roxedus** [comment] 2021-03-12 12:33
@Safihre when ubuntu released unrar 6 to the non-free package, they seem to have renamed the binary it seems. Trying to see if this is referenced somewhere. [ubuntu repo](https://packages.ubuntu.com/search?keywords=unrar&searchon=names&section=all)

**Comment by sanderjo** [comment] 2021-03-12 12:59
Ubuntu 20.04 docker container, fully updated, everything fine:
```
root@57c556df66d5:/# apt install unrar
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following NEW packages will be installed:
  unrar
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 113 kB of archives.
After this operation, 406 kB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu focal/multiverse amd64 unrar amd64 1:5.6.6-2build1 [113 kB]
Fetched 113 kB in 0s (652 kB/s)
debconf: delaying package configuration, since apt-utils is not installed
Selecting previously unselected package unrar.
(Reading database ... 4121 files and directories currently installed.)
Preparing to unpack .../unrar_1%3a5.6.6-2build1_amd64.deb ...
Unpacking unrar (1:5.6.6-2build1) ...
Setting up unrar (1:5.6.6-2build1) ...
update-alternatives: using /usr/bin/unrar-nonfree to provide /usr/bin/unrar (unrar) in auto mode
update-alternatives: warning: skip creation of /usr/share/man/man1/unrar.1.gz because associated file /usr/share/man/man1/unrar-nonfree.1.gz (of link group unrar) doesn't exist
root@57c556df66d5:/#

```

The result looks good:
```
root@57c556df66d5:/# unrar | head -2

UNRAR 5.61 beta 1 freeware      Copyright (c) 1993-2018 Alexander Roshal
root@57c556df66d5:/#
root@57c556df66d5:/# which unrar
/usr/bin/unrar
```

**Comment by sanderjo** [comment] 2021-03-12 13:01
I think the cause is in jcfp ppa: unrar is now in http://ppa.launchpad.net/jcfp/sab-addons

I'll check that. BRB

**Comment by jcfp** [comment] 2021-03-12 13:18
Looks like some compatiblity issue with the way the alternatives mechanism is handled, resulting in a missing symlink (for fresh installs only). I replaced the full backport of 6.0.3-1 for bionic with one that uses the outdated packaging style found in 5.5.8.

@sanderjo: as far as I can tell, this issue only shows on fresh installs. If you find other versions than bionic affected, let me know.

**Comment by sanderjo** [comment] 2021-03-12 13:30
Ah, bionic 18.04 ... I'll have to check that

**Comment by jcfp** [comment] 2021-03-12 14:07
> EDIT: I cannot reproduce any problem on 18.04: after adding ppa:jcfp/sab-addons, inrar is nicely version 6.00, and working.

Alright, should be fixed then by the new upload.

**Comment by anty57** [comment] 2021-03-12 15:10
> I have moved back to tag `3.1.1-ls16` and pulled following image as a temp workaround ghcr.io/linuxserver/sabnzbd:3.1.1-ls16 until this gets fixed or changes needed get communicated by sabnzbd themselves, this is not just linuxserver issue as I seen the issue on install direct on ubuntu before moving to this container.

I am using tag sabnzbd:3.2.0-ls19 is working

**Comment by Roxedus** [comment] 2021-03-12 15:23
`3.2.0-ls21` is built with @jcfp's new upload. It is now seeing the [unrar binary](https://ci-tests.linuxserver.io/linuxserver/sabnzbd/3.2.0-ls21/index.html).

**Closed by Roxedus** 2021-03-12 15:23 UTC
