### ISSUE TITLE
Tag Latest for version  Missing sabctools

### ISSUE THREAD

**Issue by akkingderf** [linuxserver/docker-sabnzbd#192] opened 2023-06-20 15:39 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Container fails to load.

### Expected Behavior

For the container to complete loading.

### Steps To Reproduce

Load the latest container and have to roll back due to rolling error.

### Environment

```markdown
- OS: Linux 64
- How docker service was installed: Docker app on a Synology NAS.
```

### CPU architecture

x86-64

### Docker creation

```bash
Load the image from the app, then build container by creating a new container from Images.
```

### Container logs

```bash
2023-06-20T15:31:35.834846033Z	stdout	Missing module: sabctools
2023-06-20T15:31:35.834675661Z	stdout	Not all required Python modules are available, please check requirements.txt
2023-06-20T15:31:34.716850022Z	stdout	If you still experience problems, remove all .pyc files in this folder and subfolders
2023-06-20T15:31:34.716787391Z	stdout	You can read more at: https://sabnzbd.org/wiki/installation/install-off-modules
2023-06-20T15:31:34.716720071Z	stdout	Missing module: sabctools
2023-06-20T15:31:34.716298938Z	stdout	Not all required Python modules are available, please check requirements.txt
2023-06-20T15:31:33.598363547Z	stdout	If you still experience problems, remove all .pyc files in this folder and subfolders
2023-06-20T15:31:33.598302057Z	stdout	You can read more at: https://sabnzbd.org/wiki/installation/install-off-modules
2023-06-20T15:31:33.598236356Z	stdout	Missing module: sabctools
2023-06-20T15:31:33.597818763Z	stdout	Not all required Python modules are available, please check requirements.txt
2023-06-20T15:31:32.480985581Z	stdout	If you still experience problems, remove all .pyc files in this folder and subfolders
2023-06-20T15:31:32.480939871Z	stdout	You can read more at: https://sabnzbd.org/wiki/installation/install-off-modules
2023-06-20T15:31:32.480897201Z	stdout	Missing module: sabctools
2023-06-20T15:31:32.480755060Z	stdout	Not all required Python modules are available, please check requirements.txt
2023-06-20T15:31:31.362129283Z	stdout	If you still experience problems, remove all .pyc files in this folder and subfolders
2023-06-20T15:31:31.362082283Z	stdout	You can read more at: https://sabnzbd.org/wiki/installation/install-off-modules
2023-06-20T15:31:31.362028663Z	stdout	Missing module: sabctools
2023-06-20T15:31:31.361646669Z	stdout	Not all required Python modules are available, please check requirements.txt
2023-06-20T15:31:30.239940418Z	stdout	If you still experience problems, remove all .pyc files in this folder and subfolders
2023-06-20T15:31:30.239902958Z	stdout	You can read more at: https://sabnzbd.org/wiki/installation/install-off-modules
2023-06-20T15:31:30.239863837Z	stdout	Missing module: sabctools
2023-06-20T15:31:30.239538485Z	stdout	Not all required Python modules are available, please check requirements.txt
2023-06-20T15:31:27.731530067Z	stdout	[custom-init] No custom files found, skipping...
```

**Comment by Roxedus** [comment] 2023-06-20 15:42
Dupe of pinned issue, #188

**Closed by Roxedus** 2023-06-20 15:42 UTC
