### ISSUE TITLE
[BUG] Doesn't start anymore

### ISSUE THREAD

**Issue by LapinFou** [linuxserver/docker-sabnzbd#188] opened 2023-05-18 16:20 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

With the latest version **4.0.1-ls108**, sabnzbd doesn't start anymore.

### Steps To Reproduce

Just install the latest version

### CPU architecture

x86-64

### Docker creation

```bash
version: "3.5"
services:
  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    environment:
      - PUID=1052
      - PGID=100
      - TZ=Europe/Paris
    volumes:
      - /volume1/download:/downloads
      - /volume1/docker/sabnzbd/config:/config
      - /volume1/docker/sabnzbd/scripts:/scripts
    ports:
      - 8080:8080
    restart: unless-stopped
```

### Container logs

```bash
[migrations] started
[migrations] no migrations found
───────────────────────────────────────

      ██╗     ███████╗██╗ ██████╗ 
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝ 
   Brought to you by linuxserver.io
───────────────────────────────────────
To support the app dev(s) visit:
SABnzbd: https://sabnzbd.org/donate
To support LSIO projects visit:
https://www.linuxserver.io/donate/
───────────────────────────────────────
GID/UID
───────────────────────────────────────
User UID:    1052
User GID:    100
───────────────────────────────────────
[custom-init] No custom files found, skipping...
Not all required Python modules are available, please check requirements.txt
Missing module: sabctools
You can read more at: https://sabnzbd.org/wiki/installation/install-off-modules
If you still experience problems, remove all .pyc files in this folder and subfolders
Not all required Python modules are available, please check requirements.txt
Missing module: sabctools
You can read more at: https://sabnzbd.org/wiki/installation/install-off-modules
If you still experience problems, remove all .pyc files in this folder and subfolders
Not all required Python modules are available, please check requirements.txt
Missing module: sabctools
You can read more at: https://sabnzbd.org/wiki/installation/install-off-modules
If you still experience problems, remove all .pyc files in this folder and subfolders
Not all required Python modules are available, please check requirements.txt
Missing module: sabctools
You can read more at: https://sabnzbd.org/wiki/installation/install-off-modules
If you still experience problems, remove all .pyc files in this folder and subfolders
Not all required Python modules are available, please check requirements.txt
Missing module: sabctools
You can read more at: https://sabnzbd.org/wiki/installation/install-off-modules
If you still experience problems, remove all .pyc files in this folder and subfolders
Not all required Python modules are available, please check requirements.txt
Missing module: sabctools
You can read more at: https://sabnzbd.org/wiki/installation/install-off-modules
If you still experience problems, remove all .pyc files in this folder and subfolders
Not all required Python modules are available, please check requirements.txt
```

**Comment by chris41g** [comment] 2023-05-18 16:25
Im having the same issue, tried repulling, tried deleting image and repulling. recreated container. same thing

**Comment by chris41g** [comment] 2023-05-18 16:36
> Im having the same issue, tried repulling, tried deleting image and repulling. recreated container. same thing

pulling [4.0.1-ls107](https://hub.docker.com/layers/linuxserver/sabnzbd/4.0.1-ls107/images/sha256-3f78f6af80f1a149278dfb8e3d825e2f59383e4c09c3abd277f37812fd17374b?context=explore)
instead of latest fixed the issue for me

**Comment by thespad** [comment] 2023-05-18 16:54
Please can you provide the full output of `docker inspect sabnzbd` as well as confirming whether you're using Portainer for deployment, and which version of Docker you are running.

**Comment by DarrenYOW** [comment] 2023-05-18 19:24
Same issue for me. Reverted to 4.0.0 instead of latest fixed the issue.

**Comment by thespad** [comment] 2023-05-18 19:26
"Me too" doesn't help anyone, please provide useful information that might enable us to identify a cause.

**Comment by chris41g** [comment] 2023-05-18 19:31
> Please can you provide the full output of `docker inspect sabnzbd` as well as confirming whether you're using Portainer for deployment, and which version of Docker you are running.

`$ sudo docker inspect sabnzbd
[
    {
        "Id": "69346852e105e2595609199931fde8dc58858118d9bd05a6fde5f0944a683c9b",
        "Created": "2023-05-18T16:34:27.765589732Z",
        "Path": "/init",
        "Args": [],
        "State": {
            "Status": "running",
            "Running": true,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 23381,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2023-05-18T16:34:33.939068731Z",
            "FinishedAt": "0001-01-01T00:00:00Z",
            "StartedTs": 1684427673,
            "FinishedTs": -62135596800
        },
        "Image": "sha256:8f639bfd7d9e1ff8995446f44edfc0a581f81c731c9c1ae6f0d3e30ea997d4ce",
        "ResolvConfPath": "/volume1/@docker/containers/69346852e105e2595609199931fde8dc58858118d9bd05a6fde5f0944a683c9b/resolv.conf",
        "HostnamePath": "/volume1/@docker/containers/69346852e105e2595609199931fde8dc58858118d9bd05a6fde5f0944a683c9b/hostname",
        "HostsPath": "/volume1/@docker/containers/69346852e105e2595609199931fde8dc58858118d9bd05a6fde5f0944a683c9b/hosts",
        "LogPath": "/volume1/@docker/containers/69346852e105e2595609199931fde8dc58858118d9bd05a6fde5f0944a683c9b/log.db",
        "Name": "/sabnzbd",
        "RestartCount": 0,
        "Driver": "btrfs",
        "Platform": "linux",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "docker-default",
        "ExecIDs": null,
        "HostConfig": {
            "Binds": [
                "/volume1/docker/sabnzbd:/config",
                "/volume1/media:/media"
            ],
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "db",
                "Config": {}
            },
            "NetworkMode": "host",
            "PortBindings": {},
            "RestartPolicy": {
                "Name": "unless-stopped",
                "MaximumRetryCount": 0
            },
            "AutoRemove": false,
            "VolumeDriver": "",
            "VolumesFrom": null,
            "CapAdd": [
                "AUDIT_WRITE",
                "CHOWN",
                "DAC_OVERRIDE",
                "FOWNER",
                "FSETID",
                "KILL",
                "MKNOD",
                "NET_BIND_SERVICE",
                "NET_RAW",
                "SETFCAP",
                "SETGID",
                "SETPCAP",
                "SETUID",
                "SYS_CHROOT"
            ],
            "CapDrop": [
                "AUDIT_CONTROL",
                "BLOCK_SUSPEND",
                "DAC_READ_SEARCH",
                "IPC_LOCK",
                "IPC_OWNER",
                "LEASE",
                "LINUX_IMMUTABLE",
                "MAC_ADMIN",
                "MAC_OVERRIDE",
                "NET_ADMIN",
                "NET_BROADCAST",
                "SYSLOG",
                "SYS_ADMIN",
                "SYS_BOOT",
                "SYS_MODULE",
                "SYS_NICE",
                "SYS_PACCT",
                "SYS_PTRACE",
                "SYS_RAWIO",
                "SYS_RESOURCE",
                "SYS_TIME",
                "SYS_TTY_CONFIG",
                "WAKE_ALARM"
            ],
            "CgroupnsMode": "host",
            "Dns": [],
            "DnsOptions": null,
            "DnsSearch": null,
            "ExtraHosts": [],
            "GroupAdd": null,
            "IpcMode": "private",
            "Cgroup": "",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "",
            "Privileged": false,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": null,
            "UTSMode": "",
            "UsernsMode": "",
            "ShmSize": 67108864,
            "Runtime": "runc",
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "PS1=$(whoami)@$(hostname):$(pwd)\\$",
                "HOME=/config",
                "TERM=xterm",
                "S6_CMD_WAIT_FOR_SERVICES_MAXTIME=0",
                "S6_VERBOSITY=1",
                "S6_STAGE2_HOOK=/docker-mods",
                "VIRTUAL_ENV=/lsiopy",
                "LSIO_FIRST_PARTY=true",
                "PYTHONIOENCODING=utf-8",
                "LANGUAGE=en_US.UTF-8",
                "LANG=en_US.UTF-8",
                "PUID=1026",
                "PGID=100",
                "UMASK=022"
            ],
            "ConsoleSize": [
                0,
                0
            ],
            "Isolation": "",
            "CpuShares": 0,
            "Memory": 0,
            "NanoCpus": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": null,
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpuRealtimePeriod": 0,
            "CpuRealtimeRuntime": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": [],
            "DeviceCgroupRules": null,
            "DeviceRequests": [],
            "KernelMemory": 0,
            "KernelMemoryTCP": 0,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": null,
            "OomKillDisable": false,
            "PidsLimit": null,
            "Ulimits": null,
            "CpuCount": 0,
            "CpuPercent": 0,
            "IOMaximumIOps": 0,
            "IOMaximumBandwidth": 0,
            "MaskedPaths": [
                "/proc/asound",
                "/proc/acpi",
                "/proc/kcore",
                "/proc/keys",
                "/proc/latency_stats",
                "/proc/timer_list",
                "/proc/timer_stats",
                "/proc/sched_debug",
                "/proc/scsi",
                "/sys/firmware"
            ],
            "ReadonlyPaths": [
                "/proc/bus",
                "/proc/fs",
                "/proc/irq",
                "/proc/sys",
                "/proc/sysrq-trigger"
            ],
            "Init": false
        },
        "GraphDriver": {
            "Data": null,
            "Name": "btrfs"
        },
        "Mounts": [
            {
                "Type": "bind",
                "Source": "/volume1/docker/sabnzbd",
                "Destination": "/config",
                "Mode": "",
                "RW": true,
                "Propagation": "rprivate"
            },
            {
                "Type": "bind",
                "Source": "/volume1/media",
                "Destination": "/media",
                "Mode": "",
                "RW": true,
                "Propagation": "rprivate"
            }
        ],
        "Config": {
            "Hostname": "nasbox",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "8080/tcp": {}
            },
            "Tty": true,
            "OpenStdin": true,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "PS1=$(whoami)@$(hostname):$(pwd)\\$",
                "HOME=/config",
                "TERM=xterm",
                "S6_CMD_WAIT_FOR_SERVICES_MAXTIME=0",
                "S6_VERBOSITY=1",
                "S6_STAGE2_HOOK=/docker-mods",
                "VIRTUAL_ENV=/lsiopy",
                "LSIO_FIRST_PARTY=true",
                "PYTHONIOENCODING=utf-8",
                "LANGUAGE=en_US.UTF-8",
                "LANG=en_US.UTF-8",
                "PUID=1026",
                "PGID=100",
                "UMASK=022"
            ],
            "Cmd": null,
            "Image": "linuxserver/sabnzbd:4.0.1-ls107",
            "Volumes": {
                "/config": {},
                "/media": {}
            },
            "WorkingDir": "/",
            "Entrypoint": [
                "/init"
            ],
            "OnBuild": null,
            "Labels": {
                "build_version": "Linuxserver.io version:- 4.0.1-ls108 Build-date:- 2023-05-18T10:16:33+00:00",
                "maintainer": "thespad",
                "org.opencontainers.image.authors": "linuxserver.io",
                "org.opencontainers.image.created": "2023-05-18T10:16:33+00:00",
                "org.opencontainers.image.description": "[Sabnzbd](http://sabnzbd.org/) makes Usenet as simple and streamlined as possible by automating everything we can. All you have to do is add an .nzb. SABnzbd takes over from there, where it will be automatically downloaded, verified, repaired, extracted and filed away with zero human interaction.",
                "org.opencontainers.image.documentation": "https://docs.linuxserver.io/images/docker-sabnzbd",
                "org.opencontainers.image.licenses": "GPL-3.0-only",
                "org.opencontainers.image.ref.name": "568de170a3940f1fcad60f8045634fc9a7eef911",
                "org.opencontainers.image.revision": "568de170a3940f1fcad60f8045634fc9a7eef911",
                "org.opencontainers.image.source": "https://github.com/linuxserver/docker-sabnzbd",
                "org.opencontainers.image.title": "Sabnzbd",
                "org.opencontainers.image.url": "https://github.com/linuxserver/docker-sabnzbd/packages",
                "org.opencontainers.image.vendor": "linuxserver.io",
                "org.opencontainers.image.version": "4.0.1-ls108"
            },
            "DDSM": false
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "4c41d760d7465e816a0ebb1034aa057e5727234b69ed7ee410da3a90e219f882",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {},
            "SandboxKey": "/var/run/docker/netns/default",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "",
            "Gateway": "",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "",
            "IPPrefixLen": 0,
            "IPv6Gateway": "",
            "MacAddress": "",
            "Networks": {
                "host": {
                    "IPAMConfig": {},
                    "Links": null,
                    "Aliases": null,
                    "NetworkID": "7c7b7d84dfe07b0f7816980c3f8ef1e9b323a136f5a2e62c12edc8bac4548dc4",
                    "EndpointID": "1e599a35e503a9ae4b53511286b96a7c68267cd3394f56c937f83ffb0a36a3e8",
                    "Gateway": "",
                    "IPAddress": "",
                    "IPPrefixLen": 0,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "",
                    "DriverOpts": null
                }
            }
        }
    }
]`

Yes I'm using portainer
`sudo docker -v
Docker version 20.10.3, build b35e731`

**Comment by gobalopper** [comment] 2023-05-18 19:38
Adding `/lsiopy/bin` to my PATH variable fixed it for me.

**Comment by thespad** [comment] 2023-05-18 20:13
Yeah it looks like Portainer is merrily copying the old envs into the recreated container whenever you do an update, nuking anything that's been updated in the new image.

**Comment by gobalopper** [comment] 2023-05-18 21:16
Mine were likely there from some old setup tutorial, I'm not using portainer. I noticed the build change in the recent commit and figured it was likely a pathing issue.

**Comment by LapinFou** [comment] 2023-05-19 15:24
I'm using Portainer 2.18.2 (BE) on a Synology NAS (916+, x86 ,CPU).
Interestingly, I rolled back to the version [4.0.1-ls107](https://hub.docker.com/layers/linuxserver/sabnzbd/4.0.1-ls107/images/sha256-3f78f6af80f1a149278dfb8e3d825e2f59383e4c09c3abd277f37812fd17374b?context=explore).
When I read the @thespad request (docker version + container info), I installed again the latest version but this time it did work! 😅

**Comment by thespad** [comment] 2023-05-19 15:28
I'm going to close this on the basis that it's not a container issue, it's an issue with Portainer overwriting the container environment when recreating it (or users manually doing the same), which breaks any changes we might make on the image (such as with this release).

**Closed by thespad** 2023-05-19 15:28 UTC

**Comment by gridlockjoe** [comment] 2023-05-21 01:56
I am getting the same error on Synology with v4.0.1-ls107. Seeing the same error text in the log:

> Not all required Python modules are available, please check requirements.txt
Missing module: sabctools
You can read more at: https://sabnzbd.org/wiki/installation/install-off-modules
If you still experience problems, remove all .pyc files in this folder and subfolders

**Comment by gobalopper** [comment] 2023-05-22 18:52
From your inspect results the issue is your PATH:
`                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",`
Either remove PATH or add `/lsiopy/bin` to the list of directories.

**Comment by gridlockjoe** [comment] 2023-05-22 19:09
> From your inspect results the issue is your PATH:
> 
> `                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",`
> 
> Either remove PATH or add `/lsiopy/bin` to the list of directories.

Thanks! I found that reloading the previous version's config through Docker brought in the old path. I recreated from scratch and all is good.

**Comment by salfter** [comment] 2023-05-24 00:47
I've been running into the same problem with sabnzbd, running on Flatcar Container Linux.  The PATH had /lsiopy/bin at the beginning, but I was still getting errors about sabctools missing.  Someone suggested rolling the Docker image back to the previous version (4.0.1-ls107).  I did that and the container started properly.  Here's where it gets weird: when I then did ```sudo systemctl stop sabnzbd && docker container rm sabnzbd && docker image prune -a && sudo systemctl start sabnzbd```, it pulled in the latest, previously troublesome image...and it worked.  I have no idea if the image changed somewhere along the way (didn't keep track of the hashes), but sabnzbd is running again.

(The way my system is set up, /etc/systemd/system/sabnzbd.service creates the container if it doesn't exist, and then starts the container.)

**Comment by shawn8888** [comment] 2023-06-12 04:25
I have tried three different approaches to resolve the issue:

1. I removed the entire PATH entry.
2. I attempted to add the PATH back and included ":/lsiopy/bin" as follows:
   PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/lsiopy/bin
3. I also tried downloading amd64-4.0.1-ls107.

Unfortunately, none of these attempts have been successful in resolving the problem. I am in need of assistance. Please help!

**Comment by shawn8888** [comment] 2023-06-12 04:41
here is the result of 
docker inspect sabnzbd
[inspect.txt](https://github.com/linuxserver/docker-sabnzbd/files/11717840/inspect.txt)

**Comment by shawn8888** [comment] 2023-06-12 04:44
here is the result of
docker inspect sabnzbd
[inspect.txt](https://github.com/linuxserver/docker-sabnzbd/files/11717870/inspect.txt)

**Comment by mrbamber** [comment] 2023-06-12 14:13
Same issue here now with the latest install today. Rolling back to 4.0.1 as above gets it back working again.

This is docker, on synology, so not a portainer issue but could well be a setup issue on my part. I followed trashes guide a couple of years ago, all been well until now. Will stay on old version for a while to see if something becomes clear.

**Comment by aptalca** [comment] 2023-06-12 14:15
@shawn8888 your PATH is wrong. Remove all user defined PATH setting and recreate the container

@mrbamber it's an issue with your PATH setting. Remove all user defined PATH setting and recreate the container

**Comment by thespad** [comment] 2023-06-12 14:16
Synology's Docker management UI has the same issue as Portainer, see https://info.linuxserver.io/issues/2023-05-22-portainer/

**Comment by mrbamber** [comment] 2023-06-12 14:34
Thanks, yeh synology docker doing the same, just clearing the path and resetting the container wouldn't get it tho, but it would allow me to ammend the path to /lsiopy/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

and then reset and run

appreciate not the best way and further issues likely but will wait for the synology fixes. Appreciate the explanation to understand what's going on and a docker issue as you say.

**Comment by thespad** [comment] 2023-06-12 14:36
Synology are unlikely to fix this, honestly. We would recommend migrating to docker compose instead.

**Comment by shawn8888** [comment] 2023-06-12 15:41
> @shawn8888 your PATH is wrong. Remove all user defined PATH setting and recreate the container

Yes, I use Synology.
What's the correct PATH? Should I delete it or add "/lsiopy/bin"
I have to admit that I haven't update docker container for a long time. Maybe that's why?

**Comment by aptalca** [comment] 2023-06-12 16:09
I don't know how Synology ui works, but it is reading the internal environment variables from the previous container and manually setting them in the new container. It causes an issue when we change the vars inside the image, because Synology is forcing the old and outdated vars.

If you can't remove it or prevent Synology from setting it manually, you can edit it, but you need to add the `/lsiopy/bin` to the beginning of `PATH`, not the end

**Comment by shawn8888** [comment] 2023-06-12 17:20
> 

Moving "/lsiopy/bin:" to the beginning of the PATH worked! 
Never thought PATH variable order has such a big impact.  
I appreciate your help!

**Comment by thew1se** [comment] 2023-06-13 19:29
I had same problem on Synolgy with Docker.
Here was how to do the fix specifically:
1. stop container
2. click on container, then edit (at top)
3. Under General Settings click Advanced Settings
4. Replace whats in PATH variable's value with: /lsiopy/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

I don't understand why this was necessary....never happened before and when rolling back to 4.01 it works fine.

**Comment by Roxedus** [comment] 2023-06-13 19:33
in NO circumstance is the fix to manually change the path. If you should do anything with it, remove it, and let the image manage it itself, like on any sane system. 

This is only necessary due to poor implementation of updates of images.

**Comment by thew1se** [comment] 2023-06-13 19:39
@Roxedus Thanks, I just tried your suggestion, which also fixed the path.  I will update my previous comment.

**Comment by irishj** [comment] 2023-06-14 20:27
I'm using docker in Synology and also manage it through portainer and experienced the same issue.

To fix, I removed the container via command line "docker rm sab" and then re-created it via command line with "docker create" and this resolved the issue, just for anyone using docker on Synology or managing through Portainer.

**Comment by akkingderf** [comment] 2023-06-20 15:59
Synology user. Thank you all for the work you did.  
My actions:  Stop container, Export (JIC), Delete container, Go to Images, Launch, Go through wizard (checked Path, which was correct.) PUID, GUID, Ports and folders.  Win go get some coffee.

**Comment by mrquatsch** [comment] 2023-07-04 15:22
I ran into this same problem with Portainer. I also had my stuff configured as stacks and it turns out the easiest solution for me was to stop and start the stack. That created the new container with only the appropriate envs. Hope this helps someone else!

**Comment by augmentedagent** [comment] 2023-07-18 17:57
> I ran into this same problem with Portainer. I also had my stuff configured as stacks and it turns out the easiest solution for me was to stop and start the stack. That created the new container with only the appropriate envs. Hope this helps someone else!

Portainer user. Did the usual upgrade procedure of pulling new image and recreating container. Got error as described in the issue. Based on the comments in this thread, the below fixed it.
 - stop container
 - edit/duplicate container
 - delete all the env's that Portainer creates (and subsequently applies to future containers)
 - leave only the 3 env's that LSIO specifies (PUID, PGID, TZ)
 - deploy container

I'll have to add to my run book to clean up the env's in future upgrades.

Thanks for the guidance @aptalca @thespad

**Comment by mikespub** [comment] 2023-09-09 14:37
FYI, here are a couple of ways I worked around the Synology ENV variable problem with Portainer:

https://github.com/mikespub-org/docker-quickstart-python/blob/master/synology.md

**Comment by Docfunkinstein** [comment] 2024-03-10 16:17
Anyone here using portainer, 

Only steps I took to fix the issue, was to go into the stack menu, and deploy the SABNZB stack.

Issue completely went away

**Comment by jdwoods** [comment] 2024-04-16 23:42
> I had same problem on Synolgy with Docker. Here was how to do the fix specifically:
> 
>     1. stop container
> 
>     2. Select the container by clicking it anywhere,  then click edit (at top)
> 
>     3. Under General Settings tab click Advanced Settings
> 
>     4. Click the PATH variable, then DELETE, then Save.
> 
>     5. Reset the container, then start.
> 
> 
> I don't understand why this was necessary....never happened before and when rolling back to 4.01 it works fine.

Just want to chime in to state that updating the container Sabnzbd in GUI Docker on a Synology NAS will still not work. The process listed above worked flawlessly and was fairly simple.

**Comment by patrickregis** [comment] 2024-10-25 05:08
> > I had same problem on Synolgy with Docker. Here was how to do the fix specifically:
> > ```
> > 1. stop container
> > 
> > 2. Select the container by clicking it anywhere,  then click edit (at top)
> > 
> > 3. Under General Settings tab click Advanced Settings
> > 
> > 4. Click the PATH variable, then DELETE, then Save.
> > 
> > 5. Reset the container, then start.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I don't understand why this was necessary....never happened before and when rolling back to 4.01 it works fine.
> 
> Just want to chime in to state that updating the container Sabnzbd in GUI Docker on a Synology NAS will still not work. The process listed above worked flawlessly and was fairly simple.

Thanks a lot , it worked like a breeze !!
