### ISSUE TITLE
[BUG] Free Disk Space issue

### ISSUE THREAD

**Issue by Fridgemagnet** [linuxserver/docker-sabnzbd#223] opened 2024-04-10 12:22 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Sabnzbd suddenly says "0 B Free Disk Space" even though the smb mount for the complete and incomplete downloads folder has over 4 TiB of free space.
Downloads are automatically paused with the error "Too little diskspace forcing PAUSE" except when testing a download (100MB/1GB/10GB) which throws the same error but resumes and finishes.
I even tried mounting the smb in the linux docker host (/etc/fstab) first and presenting it to the container as a bind mount instead of as a docker volume (see portainer stack config below).
Permissions are not the problem here as I used docker exec to create a bash session in the sabnzbd container as the "abc" (1000) user and I had no issues writing files to the downloads mount.

My configuration has not changed in the past year for sabnzbd.
The only thing which I briefly tried yesterday was to setup the linuxserver.io wireguard container and route the sabnzbd container's traffic (split tunneling) through the wireguard container according to this guide:
https://www.linuxserver.io/blog/advanced-wireguard-hub
This didn't work as I had problems publishing the sabnzbd ports when "network_mode: service:servicename" was being used and I reverted to my previous config to not use the wireguard container shortly thereafter.
Could the wireguard docker container have potentially changed/broken something on my docker host (iptables?) that could cause my current problem?

Thanks in advance for any tips/suggestions/hints.

### Expected Behavior

Correct determination of free disk space.

### Steps To Reproduce

No known trigger for problem.

### Environment

```markdown
- OS: Ubuntu 22.04.4 LTS
- How docker service was installed: Official docker setup guide
```

### CPU architecture

x86-64

### Docker creation

```bash
Portainer stack:
---
version: "3.7"
services:
  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd
    container_name: sabnzbd
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    volumes:
      - /home/serveradmin/docker/sabnzbd/config:/config
      - downloads:/mnt/sabnzbd
      #- /home/serveradmin/mount/NewsreaderDownloads:/mnt/sabnzbd
    networks:
      - usenet
    ports:
      - 8080:8080
    restart: unless-stopped
    labels:
      - docker-volume-backup.stop-during-backup=true
      - com.centurylinklabs.watchtower.enable=true

volumes:
  downloads:
    external: true
networks:
  usenet:
      driver: bridge
      name: usenet
```

### Container logs

```bash
2024-04-10 14:02:55,419::INFO::[notifier:142] Sending notification: Warning - Too little diskspace forcing PAUSE (type=warning, job_cat=None)

2024-04-10 14:02:55,419::WARNING::[assembler:155] Too little diskspace forcing PAUSE

2024-04-10 14:02:55,420::INFO::[downloader:394] Pausing

2024-04-10 14:02:55,420::INFO::[notifier:142] Sending notification: SABnzbd - Paused (type=pause_resume, job_cat=None)

2024-04-10 14:02:55,420::INFO::[downloader:414] Forcing disconnect

2024-04-10 14:02:55,420::INFO::[scheduler:409] Will resume when download_dir has more than 0 GB free space

2024-04-10 14:02:55,420::INFO::[notifier:142] Sending notification: SABnzbd - Too little diskspace forcing PAUSE (type=disk_full, job_cat=None)

2024-04-10 14:02:55,483::INFO::[assembler:88] Decoding finished /mnt/sabnzbd/incomplete/test_download_100MB/sometestfile-100MB.part11.rar
```

**Comment by homerr** [comment] 2024-04-10 19:48
Are you binding your downloads to a docker volume?

`      - downloads:/mnt/sabnzbd`

**Comment by NightHawkATL** [comment] 2024-04-11 01:36
I am getting the same errors and seeing the same issue. I have my folders mapped to a main folder that is an SMB share and I have had zero issues until today. A friend was also having the same issue and had to restore his VM to a previous day and it started working without issue. I am just now seeing the issue myself.

**Comment by NightHawkATL** [comment] 2024-04-11 04:11
I was also getting this issue on the virtual machine running Ubuntu 22.04 with docker, compose and portainer agent with all of the other containers and stacks.

![Screenshot_2024-04-10_9.47.02_PM.png](https://github.com/linuxserver/docker-sabnzbd/assets/8395658/ba71c7ed-81bf-4afb-b5b6-3ce99645834e)

**Comment by homerr** [comment] 2024-04-11 07:00
Presuming that is from the `messages` log on the host? Regardless of this fact, using network shares is not supported;

https://docs.linuxserver.io/misc/support-policy/?h=support#unsupported 

Your error 32/104's relate to the SMB service possibly getting trashed though, so you should start there and work back to docker.

**Comment by j0nnymoe** [comment] 2024-04-11 07:03
Have either of you two updated cifs-utils recently? And/or docker to v26?

**Comment by Fridgemagnet** [comment] 2024-04-11 08:28
> Have either of you two updated cifs-utils recently? And/or docker to v26?

Very good hint. I am pretty sure my "apt update && apt upgrade" cronjob ran yesterday morning and might have bumped me up to Docker v26. Or it was last Sunday and the sabnzbd container restarted for the first time yesterday.

Currently installed version: Docker version 26.0.0, build 2ae903e

**Comment by Fridgemagnet** [comment] 2024-04-11 08:29
> Are you binding your downloads to a docker volume?
> 
> ` - downloads:/mnt/sabnzbd`

Yes. Created with the following command:

`docker volume create \
  --driver local \
  --opt type=cifs \
  --opt device='//10.15.22.10/NewsreaderDownloads' \
  --opt o='username=username,password=password,vers=3.0,uid=1000,gid=1000,nobrl' \
downloads`

**Comment by Fridgemagnet** [comment] 2024-04-11 08:32
As a temporary fallback solution I installed sabnzbd on my Windows system with the exact some configuration as the linuxserver.io container and it works as expected (without a hitch).
This issue seems to be linux and/or docker related.

**Comment by homerr** [comment] 2024-04-11 15:22
Quite interesting, something somewhere must have changed. Just wondering what! NFS worked OK for me when I used to (had to) use network mounts.... yeaaaars ago now. Worked better than SMB.

**Comment by NightHawkATL** [comment] 2024-04-11 15:32
yeah, I am trying to figure out what changed as well. I just made a backup of the current state of the VM and will do an apt upgrade to see what happens after.

apt upgrade is offering these as new installs:
linux-headers-5.15.0-102
linux-headers-5.15.0-102-generic
linux-image-5.15.0-102-generic
linux-modules-5.15.0-102-generic
linux-modules-extra-5.15.0-102-generic

apt is upgrading these:
apt
apt-transport-https
apt-utils
bsdextrautils
bsdutils
containerd.io
coreutils
docker-ce
docker-ce-cli
docker-ce-rootless-extras
docker-compose-plugin
eject
ethtool
fdisk
firmware-sof-signed
libapt-pkg6.0
libblkid1
libfdisk1
libmount1
libnspr4
libnss3
libsmartcols1
libuuid1
libwbclient0
linux-generic
linux-headers-generic
linux-image-generic
mount   <<<<< **This may be the culprit**
qemu-guest-agent
snapd
update-notifier-common
util-linux
uuid-runtime

**Comment by NightHawkATL** [comment] 2024-04-11 15:39
looks like the issue is back after doing an Ubuntu APT update && upgrade. Seems to be an issue with mount, I would think but I guess I will be trying a few things to test this theory.

**Comment by NightHawkATL** [comment] 2024-04-11 18:50
tried adding some files to test with on NFS shares and sab couldn't access the nzb folder and wouldn't pull the downloads. Went back to CIFS/SMB and it works again.

At this point, it is totally an OS issue that I can see but I am not sure what it is. Not willing to do more testing without knowing where to look.

**Comment by NightHawkATL** [comment] 2024-04-11 19:37
Confirmed bug with CIFS+Kernel 5.15.0-102 - https://bugs.launchpad.net/ubuntu/+source/linux/+bug/2060780
Fix will be in 5.15.0-104 by the end of the month.

**Comment by Fridgemagnet** [comment] 2024-04-11 20:06
> Confirmed bug with CIFS+Kernel 5.15.0-102 - https://bugs.launchpad.net/ubuntu/+source/linux/+bug/2060780 Fix will be in 5.15.0-104 by the end of the month.

well done for finding, thanks for that

**Comment by NightHawkATL** [comment] 2024-04-11 20:07
Took me most of the day to find what was going on, tracing messages and errors but I finally got there lol

**Comment by NightHawkATL** [comment] 2024-04-11 20:13
@Fridgemagnet I would suggest closing this as it is not a Sab issue.

**Closed** 2024-04-11 20:30 UTC
