### ISSUE TITLE
Can't run docker inside docker since the switch to alpine

### ISSUE THREAD

**Issue by arogan** [linuxserver/docker-sabnzbd#134] opened 2022-04-21 23:26 UTC
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
Be able to run docker inside docker

## Current Behavior
Since the move to alpine you can no longer run docker inside docker.
https://stackoverflow.com/questions/68244587/docker-unable-to-find-file-in-alpine-linux-container
Please add 
apk add gcompat
during the build which fixes it.

## Steps to Reproduce

1. docker exec -it sabnzbd bash
2. docker
3.
4.

## Environment
**OS:** dietpi
**CPU architecture:** arm64

**Comment by aptalca** [comment] 2022-04-22 00:40
Too little info and way out of scope

**Closed by aptalca** 2022-04-22 00:40 UTC

**Comment by arogan** [comment] 2022-04-22 14:35
Hmm functionality that was there and is no longer there.   Clear explanation in the stackoverflow article.  Literally a 1 liner solution that will help a lot of people running on debian and debian derived solution hosts who do more advance things like calling docker inside a container.  There are quite a few binaries that target the proper architecture yet run on almost any flavor of linux BUT alpine.  This small compatibility library fixes a lot of  that.  So if you want to volume map a program from the host to inside the container then you are going to have a bad time unless you've compiled specifically for alpine.  Big regression IMO.

**Comment by Roxedus** [comment] 2022-04-22 14:54
DIND was never a intended functionality.

If your goal is to run binaries installed on the host within the container, the supported way would be a mod or custom init script to either install the compat layer, or the binary you want.

**Comment by aptalca** [comment] 2022-04-22 14:57
This is a really awful issue report. You can't provide random scattered bits of info with no context and expect people to understand what it is you're trying to do. So I'm going to have to make the following assumptions based on the bits you provided:
- You're not actually running `docker in docker` which stands for running a docker daemon inside a container
- You're just trying to call `docker-cli` from inside a container, presumably to control the docker daemon running on your host, for whatever reason that remains a mystery
- You've mapped in a random binary you got from somewhere (maybe the one on your host) into a container and expect it to work

The answer to your question is, we never ever supported mapping random binaries into a container and running them. That is not a good idea unless the binary is fully static (in your case it is clearly not). So there is no regression, as there was never any support for that.

If you want to call the docker-cli from inside a container to control the host daemon, we provide a universal docker mod: https://github.com/linuxserver/docker-mods/tree/universal-docker

We also provide a universal `docker-in-docker` mod if that's what you were after (not clear from your description): https://github.com/linuxserver/docker-mods/tree/universal-docker-in-docker

**Comment by thespad** [comment] 2022-04-22 14:59
We don't, and likely never will, support mounting host binaries into containers and executing them from there. Install your binaries into the container environment and then call them.

If, for reasons I don't think I want to know about, you want to make docker calls from inside the sab container, we already have a [mod](https://github.com/linuxserver/docker-mods/tree/universal-docker) to do that.

Finally, if you *really* want to do things the way you're suggesting, then you can just [install gcompat yourself](https://www.linuxserver.io/blog/2019-09-14-customizing-our-containers).
